// USER_VERIFY
export const USER_VERIFY_REQUEST='USER_VERIFY_REQUEST'
export const USER_VERIFY_FAILURE='USER_VERIFY_FAILURE'
export const USER_VERIFY_SUCCESS='USER_VERIFY_SUCCESS'
export const REPORTEDBY_SUCCESS='REPORTEDBY_SUCCESS'
export const USER_APPROVAL_VERIFY_SUCCESS='USER_APPROVAL_VERIFY_SUCCESS'
export const USER_REJECT_SUCCESS = 'USER_REJECT_SUCCESS'
export const REMOVE_REPORT_SUCCESS = 'REMOVE_REPORT_SUCCESS'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'



export const RESET_USERS = "RESET_USERS";
export const RESET_REPORTED_USERS = "RESET_REPORTED_USERS";
